### ISSUE TITLE
bitfire not compatible with PHP 8

### ISSUE THREAD

**Issue by s22-tech** [bitslip6/bitfire#26]
bitfire does not appear to be compatible with PHP 8.  Along with a blank screen when trying to access the dashboard, I get the following errors:

```
PHP Deprecated:  Required parameter $f follows optional parameter $max in /home/zzz/public_html/vendor/bitslip6/bitfire/cuckoo.php on line 30
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
...
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
PHP Deprecated:  Invalid characters passed for attempted conversion, these have been ignored in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 300
PHP Fatal error:  Uncaught TypeError: BitFire\generic_reducer(): Argument #4 ($value) must be of type string, array given, called in /home/zzz/public_html/vendor/bitslip6/bitfire/util.php on line 62 and defined in /home/zzz/public_html/vendor/bitslip6/bitfire/webfilter.php:219
Stack trace:
#0 /home/zzz/public_html/vendor/bitslip6/bitfire/util.php(62): BitFire\generic_reducer(Array, Array, 'cart', Array, false)
#1 /home/zzz/public_html/vendor/bitslip6/bitfire/util.php(419): TF\{closure}('cart', Array, false)
#2 /home/zzz/public_html/vendor/bitslip6/bitfire/util.php(230): TF\map_whilenot(Array, Object(Closure), false)
#3 /home/zzz/public_html/vendor/bitslip6/bitfire/webfilter.php(56): TF\Maybe->doifnot('\\TF\\map_whileno...', Array, Object(Closure), false)
#4 /home/zzz/public_html/vendor/bitslip6/bitfire/bitfire.php(455): BitFire\WebFilter->inspect(Array)
#5 /home/zzz/public_html/vendor/bitslip6/bitfire/startup.php(19): BitFire\BitFire->inspect()
#6 {main}
  thrown in /home/zzz/public_html/vendor/bitslip6/bitfire/webfilter.php on line 219
  
  
PHP Warning:  Undefined array key "ip" in /home/zzz/public_html/vendor/bitslip6/bitfire/bitfire.php on line 743
PHP Warning:  Undefined array key "ip" in /home/zzz/public_html/vendor/bitslip6/bitfire/bitfire.php on line 743
PHP Warning:  Undefined array key "ip" in /home/zzz/public_html/vendor/bitslip6/bitfire/views/dashboard.html on line 753
PHP Warning:  Undefined array key "ip" in /home/zzz/public_html/vendor/bitslip6/bitfire/views/dashboard.html on line 753
```

**Comment by bitslip6** [comment]
Resolved in 1.8.0.

Thanks so much for posting!
